---
- name: Provision PHP
  hosts: all
  roles:
    - { role: Aplyca.PHP, tags: ["php"] }
  post_tasks:
    - name: Test if PHP is installed
      shell: "php -v"
      register: result
      failed_when: "'The PHP Group' not in result.stdout"
    - name: Test if Composer is installed
      shell: "composer --version"
      register: result
      failed_when: "'Composer version' not in result.stdout"
