---
- debug: var=php verbosity=1
  tags: vars

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Composer.yml
  when: php.composer.present
  tags: composer

- include: setup-Robo.yml
  when: php.robo.present
