---
- debug: var=php verbosity=1
  tags: vars

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include Ubuntu 12.04 variables.
  include_vars: Ubuntu-lt-14.04.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('14.04', 'lt')

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Composer.yml
  when: php.composer.present
