---
- debug: var=php verbosity=1
  tags: vars

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-Composer.yml
  when: php.composer.present
  tags: composer

- include_tasks: setup-Robo.yml
  when: php.robo.present
