---
- name: Update apt cache
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_os_family == 'Debian'

- name: Ensure PHP is present using yum
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
    with_items: "{{ php['packages'] }}"
  when: ansible_os_family == 'RedHat'

- name: Ensure PHP and libraries are present using apt
  sudo: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items: php["packages"]
  when: ansible_os_family == 'Debian'
