---
- name: Add custom PHP ini
  sudo: yes
  template: src=etc/php5/mods-available/custom.ini.j2 dest=/etc/php5/mods-available/custom.ini
  when: ansible_os_family == 'Debian'

- name: Enabling custom config in PHP conf
  sudo: yes
  command: php5enmod custom
  notify: reload apache
  when: ansible_os_family == 'Debian'