---
- name: Ensure language pack is installed
  become: yes
  apt:
    name: "language-pack-en-base"

- name: Adding PPA repo for PHP
  become: yes
  apt_repository:
    repo: 'ppa:ondrej/php'
    validate_certs: no
  environment:
      LC_ALL: "C.UTF-8"

- name: Ensure PHP modules are present using apt
  become: yes
  apt:
    name: "php{{ php.version }}-{{ item.1 }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_indexed_items: "{{ php.modules }}"
  notify: reload phpserver

- name: Ensure packages are present using apt
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: "{{ php.packages }}"
  notify: reload phpserver

- name: Include setup INI settings
  include: setup.yml

- name: Enabling custom config in PHP conf
  become: yes
  command: "phpenmod -v {{ php.version }} -s {{ item.key }} {{ item.key }}"
  notify: reload phpserver
  with_dict: "{{ php.ini | default({}) }}"
  when: php.ini | length > 0
  tags: php-ini

#TODO: set read permissions to session path
