---
- name: Ensure PHP packages repos are present using yum
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: php_repos
  when: php_repos is defined

- name: Ensure PHP modules are present using yum
  become: yes
  yum:
    name: "{{ php.package }}-{{ item.1 }}"
    state: present
  with_indexed_items: "{{ php.modules }}"
  notify: reload phpserver

- include: setup.yml
