---
- name: Ensure PHP packages repos are present using yum
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: php_repos
  when: php_repos is defined

- name: Ensure PHP modules are present using yum
  sudo: yes
  yum:
    name: "{{ php['package'] }}-{{ item }}"
    state: present
  with_items: php["modules"]
  notify: reload webserver

- include: setup.yml
