---
- name: Adding PPA repo for php 5.6
  sudo: yes
  apt_repository:
    repo: 'ppa:ondrej/php5-5.6'

- name: Ensure PHP modules are present using apt
  sudo: yes
  apt:
    name: "{{ php['package'] }}-{{ item.value }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_dict: php["modules"]
  notify: reload webserver

- include: setup.yml

- name: Make PHP modules are enabled
  sudo: yes
  command: "php5enmod {{ item.value }}"
  changed_when: False
  with_dict: php["modules"]
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('14.04', 'ge')

- name: Enabling custom config in PHP conf
  sudo: yes
  command: php5enmod custom
  changed_when: False
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('14.04', 'ge')

#TODO: set read permissions to session path
