---
- name: Add custom PHP ini
  become: yes
  template:
    src: "config.ini.j2"
    dest: "/etc/php/{{ php.version }}/mods-available/{{ item.name }}.ini"
  notify: reload webserver
  with_items: "{{ php.config }}"
  tags: php-ini
