---
- name: Ensure PHP packages repos are present using yum
  sudo: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: php['repos']
  when: php['repos'] is defined

- name: Ensure PHP modules are present using yum
  sudo: yes
  yum:
    name: "{{ php['package'] }}-{{ item.value }}"
    state: present
  with_dict: php['modules']
  notify: reload webserver
  
- include: setup.yml  
