---
- name: Ensure PHP modules are present using apt
  sudo: yes
  apt:
    name: "{{ php_package }}-{{ item.value }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_dict: php_modules
  notify: reload webserver

- include: setup.yml
  
- name: Enabling custom config in PHP conf
  sudo: yes
  command: php5enmod custom
  changed_when: False
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('14.04', 'ge')
